spring.application.name=consumidor-ordem-servico
spring.profiles.active=dev

# Porta padrao
server.port=8081

# ===== GOOGLE CALENDAR (comum a todos os profiles) =====
google.calendar.credentials.file=classpath:credentials-oauth.json
google.calendar.application.name=ApiAgendamentoServices
google.calendar.tokens.directory.path=tokens

# ===== RABBITMQ (comum a todos os profiles) =====
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123456

# ===== JPA/HIBERNATE (fallback - sobrescrito por profiles) =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


